### ISSUE TITLE
error log is not written to disk

### ISSUE THREAD

**Issue by alfem** [gecos-team/gecosws-config-assistant#5]
chef client output launched from GCA is redirected to a file, but error output is not.

chef-solo.errr is always empty.

**Comment by System25** [comment]
Hi, chef-solo.err is always empty because "chef-solo" script uses a custom logger based on Mixlib::Log (https://github.com/chef/mixlib-log). And by default, Mixlib::Logger logs to STDOUT.

So, chef-solo-err is not neccessary for "chef-solo" script, but it's also used to store the STDERR output of "gem" script. 

"gem" script is used with the following parameters:
 /opt/chef/embedded/bin/gem source -r [source]
 /opt/chef/embedded/bin/gem source -a [gem_repo]

The conclusion is that "chef-solo-err" file may include error messages from "gem" script if the repos are wrong.

**Comment by alfem** [comment]
Ok, but I am afraid chef-solo execution overwrites chef-solo-err. 

Any output dumped by gem configuration will dissapear.
