### ISSUE TITLE
Workstation recipes are duplicated in GCA

### ISSUE THREAD

**Issue by alfem** [gecos-team/gecosws-config-assistant#7]
GCA package includes a copy of workstation recipes, and sometimes these are out of sync.

If we can demonstrate this copy is not necessary, it must be deleted.

I propose to split gecos-workstation-management-cookbook in two: one for GECOS Control Center policies, and one for GECOS Config Assistant recipes. This one will be the only one shipped in GCA package.

**Comment by System25** [comment]
It seems that GCA uses the following recipes:
- local (includes sssd_mgmt)
- misc_mgmt
- network_mgmt
- unlink_from_sssd
- unlink_from_gcc
- unlink_from_chef

So the following recipes aren't used:
- broadband_mgmt
  - default (includes "software_mgmt", "misc_mgmt", "network_mgmt", "users_mgmt" and "printers_mgmt")

But, since "default" recipe includes "misc_mgmt" and "network_mgmt", if you want to split the cookbook in two GECOS will have two copies of both recipes in both cookbooks.
Are you OK with this?

**Comment by juanconde** [comment]
Keep in mind that GCA can be run at any time, not always in an uninitialized node (you can run GCA to unlink from GCC or to change authentication); I mean we can not rely on recipes not to be run due to lack of corresponding data in node json.

**Comment by alfem** [comment]
Could you point at the GCA code whre misc_mgmt and network_mgmt are used? 

Perhaps it is unnecesary.

**Comment by System25** [comment]
"misc_mgmt" is used in gecosws-config-assistant/firstboot/serverconf/**init**.py to create a chef-solo script to link to the GECOS Control Center. And "network_mgmt" is used in the same file to create a chef-solo script to configure the client authentication method.

Both scripts seems to be the core of GCA.

**Comment by rcmorano** [comment]
Hi all!

I've sent a pull request (https://github.com/gecos-team/gecosws-config-assistant/pull/11) that fixes the problematic by building the gca package with the latest upstream cookbooks (gecoscc-chef-repo master branch); matching this way, the cookbooks used by the gecoscc.

**Comment by alfem** [comment]
Could you make the PR against development?

Trusty is the 'master' in these distro packages.

**Comment by rcmorano** [comment]
Done (https://github.com/gecos-team/gecosws-config-assistant/pull/12)!

**Comment by rcmorano** [comment]
I just realized that there was an error initializing git sub-subdmoules, so I sent a new PR (https://github.com/gecos-team/gecosws-config-assistant/pull/13).

Bests!
